### ISSUE TITLE
Agregar expedientes

### ISSUE THREAD

**Issue by g-mjm** [UniversidadDelEste/OpenLex#6]
Al agregar un expte. no me guarda el tipo (tipo de proceso), como tampoco el origen (juzgado o fiscalia de origen). Por que puede ser?

PD: Muy buen proyecto Marian!

**Comment by marian-vignau** [comment]
Como los posibles tipos de procesos y juzgados son muchos, lo que se utiliza es un sistema de autocompletado, esto significa que  se deben ingresar los primeros caracteres de alguna de las opciones disponibles
Para ver un listado de los tipos de procesos, ir a tablas -> tipos de procesos (http://127.0.0.1:8000/OpenLex/other_tables/tipoproceso)
Para ver un listado de los tipos de procesos, ir a juzgados (http://127.0.0.1:8000/OpenLex/other_tables/juzgados)
